# Generated by Django 4.2.13 on 2024-07-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('imgSrc', models.CharField(max_length=200)),
            ],
        ),
    ]
